# RustyHook Configuration for Rust Project

# Global settings
default_stages: [commit, push]
fail_fast: true
parallelism: 0

# Repositories configuration
repos:
  - repo: local
    hooks:
      # Standard hooks
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace
        language: system
        entry: "./target/debug/rustyhook-hooks trailing-whitespace"
        files: ".*"
        types: [text]
        stages: [commit]

      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures that a file is either empty, or ends with one newline
        language: system
        entry: "./target/debug/rustyhook-hooks end-of-file-fixer"
        files: ".*"
        types: [text]
        stages: [commit]

      - id: check-yaml
        name: Check YAML
        description: Checks yaml files for parseable syntax
        language: system
        entry: "./target/debug/rustyhook-hooks check-yaml"
        files: ".*\\.ya?ml$"
        types: [yaml]
        stages: [commit]

      - id: check-added-large-files
        name: Check for added large files
        description: Prevents giant files from being committed
        language: system
        entry: "./target/debug/rustyhook-hooks check-added-large-files --maxkb=500"
        files: ".*"
        stages: [commit]

      # Rust-specific hooks
      - id: rustfmt
        name: Rust Formatter
        description: Runs rustfmt on all Rust files
        language: system
        entry: "cargo fmt --all -- --check"
        files: ".*\\.rs$"
        types: [rust]
        stages: [commit]

      - id: cargo-check
        name: Rust Check
        description: Checks the code for errors
        language: system
        entry: "cargo check"
        files: ".*\\.rs$"
        types: [rust]
        stages: [commit]

      - id: cargo-clippy
        name: Rust Clippy
        description: Runs clippy on all Rust files
        language: system
        entry: "cargo clippy -- -D warnings"
        files: ".*\\.rs$"
        types: [rust]
        stages: [commit]
