# RustyHook Configuration

# Global settings
default_stages: [commit]
fail_fast: false

# Repositories and hooks
repos:
  - repo: local
    hooks:
      - id: example-hook
        name: Example Hook
        entry: echo "Example hook running"
        language: system
        files: ".*\\.rs$"
        stages: [commit]