# YAML Schema for RustyHook Configuration
# This schema defines the structure and validation rules for RustyHook configuration files

$schema: http://json-schema.org/draft-07/schema#
title: RustyHook Configuration
description: Configuration schema for RustyHook, a blazing-fast, Rust-native Git hook runner
type: object
properties:
  default_stages:
    type: array
    description: Default stages to run hooks on
    items:
      type: string
    default:
      - commit
  fail_fast:
    type: boolean
    description: Whether to stop running hooks after the first failure
    default: false
  parallelism:
    type: integer
    description: Maximum number of hooks to run in parallel (0 means unlimited)
    minimum: 0
    default: 0
  repos:
    type: array
    description: List of repositories containing hooks
    items:
      type: object
      properties:
        repo:
          type: string
          description: Repository identifier
        hooks:
          type: array
          description: List of hooks in this repository
          items:
            type: object
            properties:
              id:
                type: string
                description: Hook identifier
              name:
                type: string
                description: Human-readable name
              entry:
                type: string
                description: Command or script to run
              language:
                type: string
                description: Programming language or environment
              files:
                type: string
                description: File pattern to match
                default: ""
              stages:
                type: array
                description: Stages to run this hook on
                items:
                  type: string
                default:
                  - commit
              args:
                type: array
                description: Additional arguments to pass to the hook
                items:
                  type: string
                default: []
              env:
                type: object
                description: Additional environment variables
                additionalProperties:
                  type: string
                default: {}
              version:
                type:
                  - string
                  - "null"
                description: Version of the tool to use
            required:
              - id
              - name
              - entry
              - language
      required:
        - repo
        - hooks
required:
  - repos
