name: Publish to Cargo

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    with:
      run_tests: true

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Verify Cargo.toml version
      run: |
        CARGO_VERSION=$(grep '^version' Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
        if [ "$CARGO_VERSION" != "${{ needs.build.outputs.version }}" ]; then
          echo "Error: Version in Cargo.toml ($CARGO_VERSION) does not match release tag (${{ needs.build.outputs.version }})"
          exit 1
        fi

    - name: Login to crates.io
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${{ secrets.CRATES_IO_TOKEN }}

    - name: Publish to crates.io
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --no-verify
