name: Publish to GitHub Container Registry

on:
  release:
    types: [created]

jobs:
  build-and-push:
    name: Build and push Docker image to GHCR
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/rustyhook
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          latest
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rustyhook:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rustyhook:buildcache,mode=max
    
    - name: Update container description
      uses: peter-evans/dockerhub-description@v3
      with:
        registry: ghcr.io
        repository: ${{ github.repository_owner }}/rustyhook
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        short-description: "Blazing-fast, Rust-native Git hook runner"
        readme-filepath: ./README.md